### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by lukeorland** [mattusifer/s3ed#2]
This project looks really cool, so I tried to install via my spacemacs config, but it looks like there isn't a package yet on MELPA or spacelpa.

**Comment by mattusifer** [comment]
Thank you @lukeorland! That's all the motivation I needed to make this project more official. I'll close this issue when the package is on MELPA.

https://github.com/melpa/melpa/pull/5251

**Comment by mattusifer** [comment]
Done! Feel free to open up other issues if they come up, I'd love to hear your feedback.
