### ISSUE TITLE
s3ed breaks the minibuffer

### ISSUE THREAD

**Issue by Malabarba** [mattusifer/s3ed#26]
Hi there @mattusifer,
First of all, thanks for this package. It's been super useful for me on a daily basis.

Since the last time I updated, I'm running into an issue with s3ed-mode which breaks the backspace key on the minibuffer for everything else.
Steps to reproduce:

- call `s3ed-find-file`.
- answer `y` to the prompt.
- visit a bucket.

Once that is done, the problem is now activated. Whenever I'm trying to use the minibuffer for any other reason (say, good old `C-x C-f`), if I hit `backspace` I get the following error:

```
Debugger entered--Lisp error: (void-variable base)
  #f(compiled-function () (interactive nil) #<bytecode 0xb4797c153aeae80>)()
  funcall-interactively(#f(compiled-function () (interactive nil) #<bytecode 0xb4797c153aeae80>))
  call-interactively(#f(compiled-function () (interactive nil) #<bytecode 0xb4797c153aeae80>) nil nil)
  command-execute(#f(compiled-function () (interactive nil) #<bytecode 0xb4797c153aeae80>))
  read-from-minibuffer(...)
  completing-read-default(...)
  completing-read(...)
  read-file-name-default(...)
  read-file-name(...)
  find-file-read-args(...)
  byte-code(...)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

Clicking on the compiled function on the second like shows this:

```
byte code:
  args: nil
 interactive: nil
0       constant  s3ed-completing-read-backspace
1       varref    base
2       call      1
3       return    
```

**Comment by Malabarba** [comment]
I've actually had this problem for a long time, but I was working around it by doing `(define-key s3ed-mode-map (kbd "<backspace>") nil)`. 
Since the last update, however, my workaround doesn't work anymore and the problem keeps happening even after I disable s3ed-mode.

**Comment by mattusifer** [comment]
Thanks for letting me know, sorry to hear the backspace is giving you trouble. It's interesting, I hadn't seen that before, but it's because I use ido (which apparently overrides with its own backspace behavior), I disabled ido mode and was able to reproduce the issue. I'll take a look at how best to fix it.

**Comment by mattusifer** [comment]
Manually unbinding backspace in the completing read function (linked PR #27) seems to resolve the issue. Feel free to re-open if the issue persists.
